# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Code4Lib
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  We are developers and technologists for libraries, museums, and archives who are dedicated to 
  being a diverse and inclusive community, seeking to share ideas and build collaboration.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://code4lib.org" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/files/logo/c4l_logo/c4l_logo.RGB_400px.png"
logo_alt: "Code4Lib"
include: ['_pages']

header_pages:
  - about.md

#  - music  last.fm's group pages taken down
#  - https://shop.spreadshirt.com/code4lib/

# external links are in _includes/header.html


twitter_username: code4lib
github_username:  code4lib
youtube_username: code4lib
mastodon_instance: code4lib.social

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
